// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaftJzLJGz20qxTxo_YfTPv1_wUR_6BTw',
    appId: '1:431152355829:web:8e5b6a7dcbd304b0cf28bc',
    messagingSenderId: '431152355829',
    projectId: 'liferpg-2f2ae',
    authDomain: 'liferpg-2f2ae.firebaseapp.com',
    storageBucket: 'liferpg-2f2ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbCYFep0OXXIOrYPV6hY8tiYWQGFSuWr4',
    appId: '1:431152355829:android:c256a2a89a952799cf28bc',
    messagingSenderId: '431152355829',
    projectId: 'liferpg-2f2ae',
    storageBucket: 'liferpg-2f2ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxLa3llD0HHlITu3byLufanxKzFHmnkug',
    appId: '1:431152355829:ios:fdc7f11b06a1d509cf28bc',
    messagingSenderId: '431152355829',
    projectId: 'liferpg-2f2ae',
    storageBucket: 'liferpg-2f2ae.firebasestorage.app',
    iosBundleId: 'com.example.liferpg2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxLa3llD0HHlITu3byLufanxKzFHmnkug',
    appId: '1:431152355829:ios:fdc7f11b06a1d509cf28bc',
    messagingSenderId: '431152355829',
    projectId: 'liferpg-2f2ae',
    storageBucket: 'liferpg-2f2ae.firebasestorage.app',
    iosBundleId: 'com.example.liferpg2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaftJzLJGz20qxTxo_YfTPv1_wUR_6BTw',
    appId: '1:431152355829:web:a1777d76bd07ab90cf28bc',
    messagingSenderId: '431152355829',
    projectId: 'liferpg-2f2ae',
    authDomain: 'liferpg-2f2ae.firebaseapp.com',
    storageBucket: 'liferpg-2f2ae.firebasestorage.app',
  );
}
